### ISSUE TITLE
Please provide some description of how to use this plugin

### ISSUE THREAD

**Issue by centic9** [alenkacz/gradle-json-validator#1]
I am looking for a way to validate JSON as part of a Gradle build and found your project. It looks quite promision, but I could not found any description and I don't know much about Gradle, could you add a short piece of description/documentation so others can make use of your work here?

**Comment by alenkacz** [comment]
I'll do it in the next two days. Hang in there! :-)

**Comment by foragerr** [comment]
Guessing from source:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'cz.alenkacz.gradle:json-validator:0.9.9'
    }
}

apply plugin: 'cz.alenkacz.gradle.jsonvalidator'

validateJson.jsonSchema = new File('/path/to/schema')
validateJson.targetJsonFile = new File('/path/to/jsonFile')
```

**Comment by centic9** [comment]
See also the discussion at http://stackoverflow.com/questions/35854075/

**Comment by alenkacz** [comment]
I have improved the readme file. If you still have problems, let me know (but I have tested it in new project recently and it works).

**Comment by centic9** [comment]
That looks very nice, thank you. I am already using it in my project successfully!
