### ISSUE TITLE
How does the validator choose which files to validate?

### ISSUE THREAD

**Issue by tzvatot** [alenkacz/gradle-json-validator#12]
If I want to validate ALL the jsons in the project, I can provide the root directory. But it's not clear from the README how will the validator identify the files to validate? will it scan for *.json files? or any file that is in the directory will be validated?

**Comment by tzvatot** [comment]
[Duplicated](https://github.com/alenkacz/gradle-json-validator/issues/10)

**Comment by alenkacz** [comment]
@tzvatot sorry for such a late reply - yes, the behavior right not is that it will fail for non-json file. I'll implement #10 this week to allow the use case you are describing

**Comment by alenkacz** [comment]
@tzvatot please use onlyWithJsonExtension in 1.2.0

**Comment by tzvatot** [comment]
Thanks @alenkacz .
Does it run recursively on the target folder?
