### ISSUE TITLE
Possibility to validate multiple files

### ISSUE THREAD

**Issue by keppi2** [alenkacz/gradle-json-validator#8]
Hey there,
is there any possibility to validate multiple files? E.g. by giving the validator a directory or expression with wildcards?

Regards
Marius

**Comment by alenkacz** [comment]
Hi @keppi2 I have just release version 1.1.0 that contains new property making it possible to validate multiple files within a folder

https://github.com/alenkacz/gradle-json-validator/releases/tag/1.1.0

Let me know if it works for you :-)
